"""Initial clean migration

Revision ID: c063fa819963
Revises: 
Create Date: 2025-07-15 00:40:21.603359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c063fa819963"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "discountcode",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("discount_type", sa.String(length=20), nullable=False),
        sa.Column("discount_value", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column(
            "minimum_order_amount", sa.DECIMAL(precision=10, scale=2), nullable=True
        ),
        sa.Column(
            "maximum_discount_amount", sa.DECIMAL(precision=10, scale=2), nullable=True
        ),
        sa.Column("usage_limit", sa.Integer(), nullable=True),
        sa.Column("usage_limit_per_user", sa.Integer(), nullable=True),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_discountcode")),
        sa.UniqueConstraint("code", name=op.f("uq_discountcode_code")),
    )
    op.create_index("ix_discount_code", "discountcode", ["code"], unique=False)
    op.create_index(
        "ix_discount_is_active", "discountcode", ["is_active"], unique=False
    )
    op.create_index(
        "ix_discount_valid_from", "discountcode", ["valid_from"], unique=False
    )
    op.create_index(
        "ix_discount_valid_until", "discountcode", ["valid_until"], unique=False
    )
    op.create_table(
        "product",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("short_description", sa.String(length=500), nullable=True),
        sa.Column("base_price", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_featured", sa.Boolean(), nullable=False),
        sa.Column("is_customizable", sa.Boolean(), nullable=False),
        sa.Column("meta_title", sa.String(length=200), nullable=True),
        sa.Column("meta_description", sa.String(length=500), nullable=True),
        sa.Column("specifications", sa.JSON(), nullable=True),
        sa.Column("images", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product")),
        sa.UniqueConstraint("slug", name=op.f("uq_product_slug")),
    )
    op.create_index("ix_product_is_active", "product", ["is_active"], unique=False)
    op.create_index("ix_product_is_featured", "product", ["is_featured"], unique=False)
    op.create_index("ix_product_slug", "product", ["slug"], unique=False)
    op.create_table(
        "user",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("username", sa.String(length=50), nullable=True),
        sa.Column("first_name", sa.String(length=100), nullable=True),
        sa.Column("last_name", sa.String(length=100), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("is_guest", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("session_id", sa.String(length=255), nullable=True),
        sa.Column("last_login", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
        sa.UniqueConstraint("email", name=op.f("uq_user_email")),
        sa.UniqueConstraint("username", name=op.f("uq_user_username")),
    )
    op.create_index("ix_user_email", "user", ["email"], unique=False)
    op.create_index("ix_user_session_id", "user", ["session_id"], unique=False)
    op.create_table(
        "address",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=50), nullable=True),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("company", sa.String(length=100), nullable=True),
        sa.Column("street_address_1", sa.String(length=255), nullable=False),
        sa.Column("street_address_2", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("state", sa.String(length=100), nullable=False),
        sa.Column("postal_code", sa.String(length=20), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_address_user_id_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_address")),
    )
    op.create_table(
        "cart",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_cart_user_id_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cart")),
    )
    op.create_index("ix_cart_session_id", "cart", ["session_id"], unique=False)
    op.create_index("ix_cart_user_id", "cart", ["user_id"], unique=False)
    op.create_table(
        "order",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("order_number", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("subtotal", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("tax_amount", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("shipping_amount", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("discount_amount", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("total_amount", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("shipping_address", sa.JSON(), nullable=False),
        sa.Column("billing_address", sa.JSON(), nullable=False),
        sa.Column("shipping_method", sa.String(length=100), nullable=True),
        sa.Column("tracking_number", sa.String(length=100), nullable=True),
        sa.Column("payment_status", sa.String(length=20), nullable=False),
        sa.Column("payment_method", sa.String(length=50), nullable=True),
        sa.Column("payment_provider", sa.String(length=50), nullable=True),
        sa.Column("payment_provider_id", sa.String(length=255), nullable=True),
        sa.Column("discount_code_id", sa.UUID(), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("shipped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("customer_notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["discount_code_id"],
            ["discountcode.id"],
            name=op.f("fk_order_discount_code_id_discountcode"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_order_user_id_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order")),
        sa.UniqueConstraint("order_number", name=op.f("uq_order_order_number")),
    )
    op.create_index("ix_order_number", "order", ["order_number"], unique=False)
    op.create_index(
        "ix_order_payment_status", "order", ["payment_status"], unique=False
    )
    op.create_index("ix_order_status", "order", ["status"], unique=False)
    op.create_index("ix_order_user_id", "order", ["user_id"], unique=False)
    op.create_table(
        "review",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("is_verified_purchase", sa.Boolean(), nullable=False),
        sa.Column("is_approved", sa.Boolean(), nullable=False),
        sa.Column("is_featured", sa.Boolean(), nullable=False),
        sa.Column("helpful_count", sa.Integer(), nullable=False),
        sa.Column("not_helpful_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["product.id"], name=op.f("fk_review_product_id_product")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_review_user_id_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review")),
    )
    op.create_index("ix_review_is_approved", "review", ["is_approved"], unique=False)
    op.create_index("ix_review_product_id", "review", ["product_id"], unique=False)
    op.create_index("ix_review_rating", "review", ["rating"], unique=False)
    op.create_index("ix_review_user_id", "review", ["user_id"], unique=False)
    op.create_table(
        "cartitem",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cart_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("total_price", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cart_id"], ["cart.id"], name=op.f("fk_cartitem_cart_id_cart")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["product.id"], name=op.f("fk_cartitem_product_id_product")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cartitem")),
    )
    op.create_index("ix_cartitem_cart_id", "cartitem", ["cart_id"], unique=False)
    op.create_index("ix_cartitem_product_id", "cartitem", ["product_id"], unique=False)
    op.create_table(
        "orderitem",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("product_name", sa.String(length=200), nullable=False),
        sa.Column("variant_name", sa.String(length=200), nullable=False),
        sa.Column("sku", sa.String(length=100), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("total_price", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["order.id"], name=op.f("fk_orderitem_order_id_order")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["product.id"], name=op.f("fk_orderitem_product_id_product")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orderitem")),
    )
    op.create_index("ix_orderitem_order_id", "orderitem", ["order_id"], unique=False)
    op.create_index(
        "ix_orderitem_product_id", "orderitem", ["product_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_orderitem_product_id", table_name="orderitem")
    op.drop_index("ix_orderitem_order_id", table_name="orderitem")
    op.drop_table("orderitem")
    op.drop_index("ix_cartitem_product_id", table_name="cartitem")
    op.drop_index("ix_cartitem_cart_id", table_name="cartitem")
    op.drop_table("cartitem")
    op.drop_index("ix_review_user_id", table_name="review")
    op.drop_index("ix_review_rating", table_name="review")
    op.drop_index("ix_review_product_id", table_name="review")
    op.drop_index("ix_review_is_approved", table_name="review")
    op.drop_table("review")
    op.drop_index("ix_order_user_id", table_name="order")
    op.drop_index("ix_order_status", table_name="order")
    op.drop_index("ix_order_payment_status", table_name="order")
    op.drop_index("ix_order_number", table_name="order")
    op.drop_table("order")
    op.drop_index("ix_cart_user_id", table_name="cart")
    op.drop_index("ix_cart_session_id", table_name="cart")
    op.drop_table("cart")
    op.drop_table("address")
    op.drop_index("ix_user_session_id", table_name="user")
    op.drop_index("ix_user_email", table_name="user")
    op.drop_table("user")
    op.drop_index("ix_product_slug", table_name="product")
    op.drop_index("ix_product_is_featured", table_name="product")
    op.drop_index("ix_product_is_active", table_name="product")
    op.drop_table("product")
    op.drop_index("ix_discount_valid_until", table_name="discountcode")
    op.drop_index("ix_discount_valid_from", table_name="discountcode")
    op.drop_index("ix_discount_is_active", table_name="discountcode")
    op.drop_index("ix_discount_code", table_name="discountcode")
    op.drop_table("discountcode")
    # ### end Alembic commands ###
