"""
Pydantic schemas package.
"""

# Common schemas
from .common import (
    PaginationParams,
    PaginatedResponse,
    SuccessResponse,
    StandardResponse,
    ErrorResponse,
    HealthCheck,
    TokenResponse,
    TokenData,
    ReviewBase,
    ReviewCreate,
    ReviewUpdate,
    ReviewResponse,
    ReviewHelpfulness,
    FileUploadResponse,
    BulkActionRequest,
    BulkActionResponse,
    SearchFilters,
)

# User schemas
from .user import (
    AddressBase,
    AddressCreate,
    AddressUpdate,
    AddressResponse,
    UserBase,
    UserCreate,
    UserUpdate,
    UserResponse,
    UserLogin,
    UserRegister,
    GuestUserCreate,
    PasswordChange,
    PasswordReset,
    PasswordResetConfirm,
    EmailVerificationRequest,
    ResendVerificationRequest,
)

# Product schemas
from .product import (
    CategoryBase,
    CategoryCreate,
    CategoryUpdate,
    CategoryResponse,
    ProductCustomizationBase,
    ProductCustomizationCreate,
    ProductCustomizationUpdate,
    ProductCustomizationResponse,
    ProductVariantBase,
    ProductVariantCreate,
    ProductVariantUpdate,
    ProductVariantResponse,
    ProductBase,
    ProductCreate,
    ProductUpdate,
    ProductResponse,
    ProductListResponse,
    ProductSearchRequest,
)

# Cart schemas
from .cart import (
    CartItemCustomization,
    CartItemBase,
    CartItemCreate,
    CartItemUpdate,
    CartItemResponse,
    CartBase,
    CartCreate,
    CartResponse,
    CartSummary,
    AddToCartRequest,
    UpdateCartItemRequest,
)

# Order schemas
from .order import (
    OrderStatus,
    PaymentStatus,
    OrderItemBase,
    OrderItemCreate,
    OrderItemResponse,
    OrderBase,
    OrderCreate,
    OrderUpdate,
    OrderResponse,
    OrderListResponse,
    OrderSummary,
    CheckoutRequest,
    PaymentIntent,
    DiscountCodeBase,
    DiscountCodeCreate,
    DiscountCodeUpdate,
    DiscountCodeResponse,
    DiscountValidation,
)

__all__ = [
    # Common
    "PaginationParams",
    "PaginatedResponse",
    "SuccessResponse",
    "StandardResponse",
    "ErrorResponse",
    "HealthCheck",
    "TokenResponse",
    "TokenData",
    "ReviewBase",
    "ReviewCreate",
    "ReviewUpdate",
    "ReviewResponse",
    "ReviewHelpfulness",
    "FileUploadResponse",
    "BulkActionRequest",
    "BulkActionResponse",
    "SearchFilters",
    
    # User
    "AddressBase",
    "AddressCreate",
    "AddressUpdate",
    "AddressResponse",
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserResponse",
    "UserLogin",
    "UserRegister",
    "GuestUserCreate",
    "PasswordChange",
    "PasswordReset",
    "PasswordResetConfirm",
    "EmailVerificationRequest",
    "ResendVerificationRequest",
    
    # Product
    "CategoryBase",
    "CategoryCreate",
    "CategoryUpdate",
    "CategoryResponse",
    "ProductCustomizationBase",
    "ProductCustomizationCreate",
    "ProductCustomizationUpdate",
    "ProductCustomizationResponse",
    "ProductVariantBase",
    "ProductVariantCreate",
    "ProductVariantUpdate",
    "ProductVariantResponse",
    "ProductBase",
    "ProductCreate",
    "ProductUpdate",
    "ProductResponse",
    "ProductListResponse",
    "ProductSearchRequest",
    
    # Cart
    "CartItemCustomization",
    "CartItemBase",
    "CartItemCreate",
    "CartItemUpdate",
    "CartItemResponse",
    "CartBase",
    "CartCreate",
    "CartResponse",
    "CartSummary",
    "AddToCartRequest",
    "UpdateCartItemRequest",
    
    # Order
    "OrderStatus",
    "PaymentStatus",
    "OrderItemBase",
    "OrderItemCreate",
    "OrderItemResponse",
    "OrderBase",
    "OrderCreate",
    "OrderUpdate",
    "OrderResponse",
    "OrderListResponse",
    "OrderSummary",
    "CheckoutRequest",
    "PaymentIntent",
    "DiscountCodeBase",
    "DiscountCodeCreate",
    "DiscountCodeUpdate",
    "DiscountCodeResponse",
    "DiscountValidation",
] 